language: python
python:
  - 2.7
  - 3.5
before_install:
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev
install:
  - pip install readme flake8 pydocstyle
  - pip install numpy -U
  - pip install .
before_script:
  - python setup.py check -m -r -s
  - flake8 .
  - pydocstyle . --match-dir='(?!.*tests).*'
script:
  - pytest
